name: 04 - Using Actions
on:
  - push
jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: 24
    
      - name: Install Deps
        run: npm ci
        working-directory: 04-using-actions/react-app

      - name: Run tests
        run: |
            cd 04-using-actions/react-app
            npm test


        
